jobs:
  triage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v5
      with:
        configuration-path: .github/config/labeler-config.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: false
name: Pull Request Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
permissions:
  contents: read
  pull-requests: write
